url: http://www.joeloliveira.com
name: My name is Joel
highlighter: pygments
description: >
  I work on the web making stuff (like <a href="https://shubox.io?utm_source=joeloliveira&utm_medium=web&utm_campaign=sister_app">shubox</a>
  and <a href="https://www.thredded.com">thredded</a>). I live in Boston(-ish)
  with my wife, my son, and our two english bulldogs.
