plugins:
  - jekyll-dotenv
  - jekyll-imgproxy-tag
  - jekyll-twitter-plugin
url: https://www.joeloliveira.com
name: My name is Joel
highlighter: pygments
description: >
  An eng manager working at ezCater during the day,
  making stuff like <a href="https://shubox.io?utm_source=joeloliveira&utm_medium=web&utm_campaign=sister_app">shubox</a>
  at night. Living in Brookline with my wife, our son, and our two English bulldogs - Pearl and Trudie.
imgproxy:
  base_url: https://imagesjroli.b-cdn.net
  key: ENV_IMGPROXY_KEY
  salt: ENV_IMGPROXY_SALT
  aws_bucket: ENV_AWS_BUCKET
tailwindcss:
  - input: assets/css/critical.css
    config: tailwind.critical_config.js
    minified: true
  - input: assets/css/deferred.css
    config: tailwind.deferred_config.js
    minified: true
esbuild:
  - input: assets/js/deferred.js
    outdir: assets/js
    extra_options: --format=esm --splitting
inlinecss:
  replace:
    - this: url(./font
      with: url(/assets/css/font
