url: http://joeloliveira.com
name: My name is Joel
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [footnotes, no_intra_emphasis, fenced_code_blocks, autolink, strikethrough, superscript, with_toc_data]
description: >
  I work on the web making stuff I like. I
  live in Boston(-ish) with my wife, my son,
  and our two english bulldogs.
